
[project]
name = "threefive"
version = "3.0.85"
authors = [
  { name="AdrianofDoom", email="spam@iodisco.com" },
]
description = "threefive is The #1 SCTE-35 Decoder and Encoder on the Planet."
readme = "README.md"
requires-python = ">=3.9"
dependencies=[

    ]

classifiers = [
        "Environment :: Console",
        "Operating System :: OS Independent",
        "Topic :: Multimedia :: Video",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: Implementation :: PyPy",
        "Programming Language :: Python :: Implementation :: CPython",
]

license = "Sleepycat"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/superkabuki/threefive"
Issues = "https://github.com/superkabuki/threefive/issues"

[project.scripts]
scte35bump = "threefive.bump:cli"
gums = "threefive.gums:cli"
scte35hls = "threefive.hls:cli"
scte35fix = "threefive.sixfix:cli"
scte35inject = "threefive.superkabuki:cli"
threefive = "threefive.cli:threefivecli"
