"""
Example of Encoding a Time Signal Command from Scratch
"""

import threefive3

# Create a Time Signal named cmd.
cmd = threefive3.TimeSignal()

# set the values needed
cmd.time_specified_flag = True
cmd.pts_time = 23000.677777

# Create an empty Cue, named cue.
cue = threefive3.Cue()

# set cue.command to  cmd
cue.command = cmd

# re-encode
# The Splice Info Section is automatically
# generated by threefive3 when you encode.
cue.encode()

#  run cue.show() to see the results..
cue.show()
